### ISSUE TITLE
Base layout

### ISSUE THREAD

**Issue by minettiandrea** [minettiandrea/sample-analyzer#3]
Create if from scratch?
Use a template? 
Using a framework?

Anyway I would use SCSS, that is almost 100% compatible with CSS but with a lot of very useful extra features: https://sass-lang.com/guide

**Comment by ammlyy** [comment]
These might be useful in order to have some pre-assembled components:
 https://vuematerial.io/ or https://vuetifyjs.com/en/

**Comment by minettiandrea** [comment]
Nice, I would go for vuetifyjs seems to be more supported
